Dev
nlukic97/uteam-api pull request #6
Opened 2022-02-04 12:35 UTC by nlukic97

2022-02-04 15:36 UTC, nlukic97 commented on ts/controllers/Company.controller.ts
> +        if(companyExists.User.id !== req.user.id) throw `You are not the owner of the company ${req.params.id}, and cannot change it.`; //error on user, might have to declare on Company model
Error with TypeScript for the included User model for this query - still searching for solution

2022-02-04 15:37 UTC, nlukic97 commented on ts/controllers/Company.controller.ts
> +            if(company.User.id !== req.user.id) throw `You are not the owner of the company ${req.params.id}, and cannot delete it.`; //error on user, might have to declare on Company model
Error with TypeScript for the included User model for this query - still searching for solution

2022-02-04 15:38 UTC, nlukic97 commented on ts/controllers/Profile.controller.ts
> +        if(profileExists.User.id !== req.user.id) throw `You are not the owner of the profile ${req.params.id}, and cannot change it.`; //error on user, might have to declare on Company model
Error with TypeScript for the included User model for this query - still searching for solution

2022-02-04 15:38 UTC, nlukic97 commented on ts/controllers/Profile.controller.ts
> +            if(profile.User.id !== req.user.id) throw `You are not the owner of the profile ${req.params.id}, and cannot delete it.`; //error on user, might have to declare on Profile model
4. Error with TypeScript for the included User model for this query - still searching for solution

2022-02-04 16:25 UTC, nlukic97 commented
Update: Fxed the issue highlighted in the previous two comments with this commit: 
https://github.com/nlukic97/uteam-api/pull/6/commits/0693b75f266e863333d391e3450198573e3d96fe

In short, I added the **User** attribute to the **Profile** and **Company** interfaces, and assigned **UserAttributes** (the interface for User i imported) as the value for **User**.

2022-02-22 10:11 UTC, vuxor requested changes

2022-02-22 10:11 UTC, vuxor commented on ts/ts_interfaces/User.Interface.ts
> +    role?:'company-user'|'company-admin'|'superadmin', //optional since we have a default value for enum
You can use enum instead of strings here

2022-02-22 14:30 UTC, nlukic97 commented on ts/middleware/validation/Company.update.validation.ts
> +        submitData.name = submitData.name.trim()
This commit should fix this: https://github.com/nlukic97/uteam-api/pull/6/commits/dbd60a51f47af4949aacdaa345a50eb173fa427c

2022-02-22 14:45 UTC, nlukic97 commented on ts/middleware/validation/Profile.update.validation.ts
> +            return res.status(400).json({message:'There appear to be empty fields. Please check your inputs and try again.'})
Fixed with this commit: https://github.com/nlukic97/uteam-api/commit/0c8250d3aada8479169d038636b6a586f30ea401

The code has been refactored to: 
- be more readable
- contain the specific error messages
- not contain unecessary nullchecks before trimming strings (same issue was present here as was in the validation for updating Company)

Sample: https://github.com/nlukic97/uteam-api/blob/0c8250d3aada8479169d038636b6a586f30ea401/ts/middleware/validation/Profile.update.validation.ts#L23-L25

2022-02-22 14:48 UTC, nlukic97 commented on ts/middleware/validation/Profile.update.validation.ts
> +    || (submitData.company && (Number.isInteger(submitData.company) === false || submitData.company === 0))
Fixed with the commit mentioned in the previous comment (https://github.com/nlukic97/uteam-api/commit/0c8250d3aada8479169d038636b6a586f30ea401)

2022-02-22 15:29 UTC, nlukic97 commented on ts/ts_interfaces/User.Interface.ts
> +    role?:'company-user'|'company-admin'|'superadmin', //optional since we have a default value for enum
Managed to refactor using **enum**: https://github.com/nlukic97/uteam-api/commit/96e03ec1f146964f2c1d5e47c8194d3b9ad8c3ab

2022-02-23 08:20 UTC, vuxor approved these changes

2022-02-23 11:15 UTC, merged